AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for alexa-skill-spreadsheet-organizer

Globals:
  Function:
    Timeout: 6

Parameters:
  SKILLID:
    Type: String
    Description: Alexa Skill Id
  GOOGLESPREADSHEETID:
    Type: String
    Description: Spreadsheet Id found on Google Sheets URL
  SPREADSHEETRANGE:
    Type: String
    Description: Spreadsheet range that Skill will read
  GOOGLESHEETAPIKEY:
    Type: String
    Description: API Key for Google Sheets API for public access
    Default: None

Resources:
  SpreadsheetOrganizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: source/lambda
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
          Properties:
            SkillId: !Ref SKILLID
      Environment:
        Variables:
          GOOGLESPREADSHEETID: !Ref GOOGLESPREADSHEETID
          SPREADSHEETRANGE: !Ref SPREADSHEETRANGE
          GOOGLESHEETAPIKEY: !Ref GOOGLESHEETAPIKEY

Outputs:
  SpreadsheetOrganizerFunction:
    Description: "SpreadsheetOrganizer Lambda Function ARN"
    Value: !GetAtt SpreadsheetOrganizerFunction.Arn
  SpreadsheetOrganizerFunctionIamRole:
    Description: "Implicit IAM Role created for SpreadsheetOrganizer function"
    Value: !GetAtt SpreadsheetOrganizerFunctionRole.Arn
